export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
};

export const CartActionType = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
    SAVE_SHIPPING_INFO: "SAVE_SHIPPING_INFO",
};
